"""empty message

Revision ID: 31403f944a32
Revises: cfbc6a1570bd
Create Date: 2022-10-18 19:12:02.249038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31403f944a32'
down_revision = 'cfbc6a1570bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planeta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('rotation_period', sa.Integer(), nullable=True),
    sa.Column('orbital_period', sa.Integer(), nullable=True),
    sa.Column('diameter', sa.Integer(), nullable=True),
    sa.Column('gravity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('favoritos', sa.Column('id_planeta', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'favoritos', 'planeta', ['id_planeta'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favoritos', type_='foreignkey')
    op.drop_column('favoritos', 'id_planeta')
    op.drop_table('planeta')
    # ### end Alembic commands ###
