"""empty message

Revision ID: 91fb0a89f6f4
Revises: 31403f944a32
Create Date: 2022-10-18 19:27:29.585927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91fb0a89f6f4'
down_revision = '31403f944a32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personaje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('hair_color', sa.String(length=250), nullable=True),
    sa.Column('eye_color', sa.String(length=250), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('favoritos', sa.Column('id_personaje', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'favoritos', 'personaje', ['id_personaje'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favoritos', type_='foreignkey')
    op.drop_column('favoritos', 'id_personaje')
    op.drop_table('personaje')
    # ### end Alembic commands ###
