"""empty message

Revision ID: d89c2f78f55e
Revises: 91fb0a89f6f4
Create Date: 2022-10-19 14:22:24.220231

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd89c2f78f55e'
down_revision = '91fb0a89f6f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('password', sa.Integer(), nullable=False))
    op.alter_column('usuario', 'name',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('usuario', 'last_name',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuario', 'last_name',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('usuario', 'name',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.drop_column('usuario', 'password')
    # ### end Alembic commands ###
